Title: WELCOME TO FRANKIE A DEL ROSARIO PORTHFOLIO IN EDM
show_download: true
#theme: jekyll-theme-merlot
remote_theme: pages-themes/merlot@v0.2.0
plugins:
jekyll-remote-theme # add this line to the plugins

