{
  "portfolio": {
    "name": "Frankie A. Del Rosario",
    "email": "fdelrosario24-0525@cca.edu.ph",
    "github": "https://github.com/Restia-F/fdelrosario",
    "hero_image": "https://avatars.githubusercontent.com/u/201305156?s=400&u=4097de5c6ecde91ffff528d1fc86085e86e0f41a&v=4",
    "about": {
      "bio": "I am Frankie A. Del Rosario, currently studying at City College of Angeles with a course in Bachelor of Science in Information System."
    },
    "projects": {
      "midterm": [
        {
          "title": "Midterm Lab Task 1: Data Cleaning and Preparation using EXCEL",
          "url": "https://github.com/JDelosReyes27/Nunoypogi123/tree/main/Midterm%20Task%201"
        },
        {
          "title": "Midterm Lab Task 2: Data Cleaning and Preparation using Power Query",
          "url": "https://github.com/jdelosreyes/EDM-Jerome/tree/main/Midterm%20Task%202"
        },
        {
          "title": "Midterm Lab Task 3: Creating PIVOT TABLE and DASHBOARD",
          "url": "https://github.com/jdelosreyes/EDM-Jerome/tree/main/Midterm%20Task%203"
        }
      ],
      "finals": [
        {
          "title": "Finals Lab Task 1:: Data Cleaning and Preparation using EXCEL",
          "url": "https://github.com/Restia-F/fdelrosario/tree/main/Final%20Lab%20Task%201"
        },
        {
          "title": "Finals Lab Task 2: Data Cleaning and Preparation using Power Query",
          "url": "https://github.com/Restia-F/fdelrosario/tree/main/Final%20Task%202"
        },
        {
          "title": "Finals Lab Task 3: Creating PIVOT TABLE and DASHBOARD",
          "url": "https://github.com/Restia-F/fdelrosario/tree/main/Final%20Task%203"
        },
        {
          "title": "Finals Lab Task 5: Creating PIVOT TABLE and DASHBOARD",
          "url": "https://github.com/Restia-F/fdelrosario/tree/main/Final%20Task%203.1"
        }
      ]
    }
  }
}
